Update startup.sh
ExpediaGroup/apiary-metastore-docker pull request #111
Opened 2023-03-29 17:07 UTC by DhrubajyotiSadhu

### :pencil: Description

### :link: Related Issues

2023-03-29 17:43 UTC, jmnunezizu requested changes

2023-03-29 17:43 UTC, jmnunezizu commented on files/startup.sh
> +export DD_API_KEY=$(aws secretsmanager get-secret-value --secret-id dd-analytics-platform-starburst --region us-east-1 --query 'SecretString' --output text  | jq -r '.api_key')
The secret-id must be read from an env variable. Please remove the reference.

2023-03-29 17:43 UTC, jmnunezizu commented on files/startup.sh
> +    echo "\$DD_API_KEY is empty"
Is this an error, a warning, or a valid path?

2023-03-30 10:07 UTC, javsanbel2 commented
You opened 2 PRs, this one with Jose's comments and the other with my comments from yesterday

2023-03-30 14:00 UTC, closed without merging