enable hive lock house keeper
ExpediaGroup/apiary-metastore-docker pull request #117
Opened 2023-08-07 20:55 UTC by githubjianli

Added variable `ENABLE_HIVE_LOCK_HOUSE_KEEPER` to support hive lock house keeper.

2023-08-07 21:06 UTC, alangr28 approved these changes

2023-08-07 21:15 UTC, etapiaromero approved these changes

2023-08-07 21:50 UTC, RickArt submitted a review, later dismissed

2023-08-08 08:21 UTC, patduin commented on files/startup.sh
> +    update_property.py hive.exec.dynamic.partition.mode nonstrict /etc/hive/conf/hive-site.xml
this is not needed I think

2023-08-08 08:38 UTC, abhimanyugupta07 commented on CHANGELOG.md
> +- Added variable `ENABLE_HIVE_LOCK_HOUSE_KEEPER` to support hive lock house keeper.
We can create an issue in this project and explain it there and then refer it from the CHANGELOG.

2023-08-08 11:07 UTC, patduin requested changes
In our test some properties weren't needed, please double check

2023-08-08 19:20 UTC, abhimanyugupta07 commented on CHANGELOG.md
> +## [3.0.13] - TBD
```suggestion
## [3.0.13] - 2023-08-09
```

2023-08-08 19:20 UTC, abhimanyugupta07 approved these changes

2023-08-09 09:58 UTC, patduin approved these changes

2023-08-10 22:28 UTC, merged