fix: set  default connector jar path
ExpediaGroup/apiary-metastore-docker pull request #129
Opened 2024-06-21 17:37 UTC by githubjianli

### :pencil: Description

### Fixed
- Set default `AUX_CLASSPATH` based on `MYSQL_TYPE`.
  - When `mysql`, then set to `/usr/share/java/mysql-connector-java.jar`.
  - When `mariadb` then set to `/usr/share/java/mariadb-connector-java.jar`.
  - Else set to `MYSQL_DRIVER_JAR`.
### :link: Related Issues

2024-06-21 18:12 UTC, mroark1m approved these changes

2024-06-24 09:24 UTC, DhrubajyotiSadhu approved these changes

2024-06-24 12:02 UTC, patduin requested changes
Not sure we need this, please hold off merging this for now.

2024-06-24 12:11 UTC, javsanbel2 commented
This was fixed here https://github.com/ExpediaGroup/apiary-metastore-docker/pull/129

2025-04-10 11:13 UTC, closed without merging