Enable HMS Schema Deletion
ExpediaGroup/apiary-metastore-docker pull request #79
Opened 2020-08-21 20:29 UTC by barnharts4

Add a feature to delete HMS metadata for a list of schemas specified in `HIVE_DBS_TO_DELETE` environment variable.

Corresponding Datalake Terraform PR: https://github.com/ExpediaGroup/apiary-data-lake/pull/171

2020-08-24 09:46 UTC, massdosage requested changes

2020-08-24 09:46 UTC, massdosage commented on README.md
> +|ENABLE_SCHEMA_DELETION|No|Option to delete unused Hive databases from $HIVE_DBS_TO_DELETE on startup. Enabled if value is not null/empty. NOTE: This will only delete metadata from the HMS, not actua
```suggestion
|ENABLE_SCHEMA_DELETION|No|Option to delete Hive databases from $HIVE_DBS_TO_DELETE on startup. Enabled if value is not null/empty. NOTE: This will only delete metadata from the HMS, not actual S3 data or buckets. This will also update the MySQL Hive schema to enable cascading-deletes before deleting, then will remove cascading-deletes.|
(nothing says they have to be "unused" right? there might be many reasons for deleting them)
```

2020-08-24 09:46 UTC, massdosage commented on files/create_cascade_alter_script.py
> +# Licensed to the Apache Software Foundation (ASF) under one or more
This is missing our copyright, see the .java files in other projects for a good template.

2020-08-24 09:46 UTC, massdosage commented on files/create_cascade_alter_script.py
> +    main()
Add a [closing line break](https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file) to EOF please.

2020-08-24 09:46 UTC, massdosage commented on files/startup.sh
> +        echo "Creating cascadedeletes.sql and undo_cascadedeletes.sql"
Why do we need to do this? I'm sure you have a reason but it feels risky running something like this against the Hive DB...

2020-08-24 16:16 UTC, barnharts4 commented on files/startup.sh
> +        echo "Creating cascadedeletes.sql and undo_cascadedeletes.sql"
Two reasons we do it this way:

1.  The Hive schema has a lot of interrelated tables, each of which is using referential integrity.  Trying to find and generate all of the correct statements is cumbersome, and also prone to change between versions of the Hive schema.
2. We want to do these deletes inside of a transaction so that if anything fails, it automatically does a rollback.  That would be difficult to script in our startup scripts, and would probably necessitate some Java or Python code to use JDBC to start a transaction.

Both of these needs are met by using the builtin cascading-delete functionality in the database engine itself, and presumably they have done way more testing and debugging on these features than we would have time to do.

The reason we reset the schema to NOT have cascading deletes after we do the schema deletes, is just in case Hive's metastore code is relying on non-cascading deletes for any of its internal functionality, we don't want to circumvent that.

2020-08-24 16:17 UTC, barnharts4 commented on files/create_cascade_alter_script.py
> +    main()
done

2020-08-24 16:17 UTC, barnharts4 commented on files/create_cascade_alter_script.py
> +# Licensed to the Apache Software Foundation (ASF) under one or more
done

2020-08-24 16:17 UTC, barnharts4 commented on README.md
> +|ENABLE_SCHEMA_DELETION|No|Option to delete unused Hive databases from $HIVE_DBS_TO_DELETE on startup. Enabled if value is not null/empty. NOTE: This will only delete metadata from the HMS, not actua
done

2020-08-24 17:25 UTC, massdosage commented on files/startup.sh
> +        echo "Creating cascadedeletes.sql and undo_cascadedeletes.sql"
Could this ever be a problem:

1. This code runs and enables cascading deletes
2. Some other Hive code runs and does some deletes which now cascade where they wouldn't have before.
3. Your code drops the DB and puts the cascades back

?

2020-08-24 17:26 UTC, massdosage commented on files/startup.sh
> +        cat undo_cascadedeletes.sql | mysql $MYSQL_OPTIONS
It's safe to "uncascade" everything? i.e. there isn't anything that has cascading on by default that we'd want to leave in that state?

2020-08-24 17:27 UTC, massdosage commented on files/startup.sh
> +            /bin/delete_hive_db.sh $DB_TO_DELETE
I'm a bit worried about fiddling with the internal MySQL stuff, especially around edge cases etc. I'd really rather not touch the internals if we can avoid it. Why can't we do this using the Hive shell instead?

2020-08-24 17:58 UTC, rpoluri commented on files/startup.sh
> +            /bin/delete_hive_db.sh $DB_TO_DELETE
dropping a database is Hive is not simple, depending on if tables are setup as managed/external, hive will also attempt to delete the data, we just want to cleanup deprecated database and tables.
And most to times in those scenarios Hive CLI/ Hive server2 will just keep running for hours try to cleanup.

2020-08-24 18:09 UTC, rpoluri commented on files/startup.sh
> +        echo "Creating cascadedeletes.sql and undo_cascadedeletes.sql"
Agree with @massdosage on this, toggling cascading might be risky considering we run multiple metastores and startup scripts parallelly in multiple metastores.
even though cumbersome, probably might be safer to generate all necessary SQL statements

2020-08-26 01:02 UTC, barnharts4 commented on files/startup.sh
> +        echo "Creating cascadedeletes.sql and undo_cascadedeletes.sql"
@massdosage , @rpoluri - OK, you asked for it, you got it.  Changed to using a 500-line MySQL script to delete things in the proper order.  Note it is very complex, because the Hive metastore schema does some weird stuff with (not) relating certain tables back to the `DBS` entry very well.  Or by making it really hard to delete things in order without saving off temporary tables with the keys of things that I need to delete later.

*Please* review the script very carefully.  I have tested it on the `dsp-lab` Apiary `dm` schema multiple times and it works.  But I need you guys to go over it too, since you wanted this instead of trusting MySQL to cascade deletes correctly.

2020-08-27 08:28 UTC, massdosage commented on files/startup.sh
> +            /bin/delete_hive_db.sh $DB_TO_DELETE
The above script that @barnharts4 has had to create looks like a *lot* of work, from what I can tell the only problem with using Hive to drop the DB is if there are non-external tables in it? Do we have this use case often enough that it's really an issue? If we're OK to leave the data on S3 couldn't we just have a script which loops through all the tables in the DB and sets them to external and then drops them and then drops the DB? Something using Hive rather than digging in the internals of MySQL seems much safer, less error prone and less work to me.

2020-08-27 08:32 UTC, massdosage commented on files/startup.sh
> +        echo "Creating cascadedeletes.sql and undo_cascadedeletes.sql"
Yeah, I agree this looks horrible and complex, I'm sorry you had to do this. I really don't think we should be touching the underlying RDBMs, I'd much rather look into alternatives that use Hive DDL via the CLI or the metastore API via Thrift and some kind of (Python?) script.

2020-08-27 13:05 UTC, rpoluri commented on files/startup.sh
> +            /bin/delete_hive_db.sh $DB_TO_DELETE
Hive CLI is not practical.
In on of production changes, we tried to use hive metatool to fix hive entries for upgrade, waited for 6hrs to finish the process, finally abandoned and ran mysql commands to complete process in less than a minute.
Hive way of interacting with metastore change is way overcomplicated and is not practical for anything other than individual tables.

@barnharts4 you can try using Cli, most probably won't work as hive will try to delete S3 bucket, which metastore won't be able to complete.

2020-08-27 13:40 UTC, patduin commented on files/startup.sh
> +            /bin/delete_hive_db.sh $DB_TO_DELETE
The thrift client has a `dropDatabase(name, boolean deleteData, boolean ignoreUnknownDb)` would that work?

2020-08-27 13:49 UTC, rpoluri commented on files/startup.sh
> +            /bin/delete_hive_db.sh $DB_TO_DELETE
Possibly, @barnharts4 lets test that quickly to see if it is a viable option.

2020-11-18 18:59 UTC, closed without merging

2020-11-18 19:00 UTC, barnharts4 commented
Closing this as it was accomplished a different way.