remove atlas metastore listener
ExpediaGroup/apiary-metastore-docker pull request #87
Opened 2021-04-26 17:07 UTC by LulaV14

### :pencil: Description

### :link: Related Issues

2021-04-27 18:13 UTC, barnharts4 requested changes
Since we now send events to HiveAtlasShim just through configuring `KAFKA_BOOTSTRAP_SERVERS` and `KAFKA_TOPIC_NAME`, I think you can get rid of everything Atlas related in this project.  There were some you didn't delete, like building Atlas in the Dockerfile.

Also, you need to add `kafka-clients-<version>.jar` to the classpath whenever `KAFKA_BOOTSTRAP_SERVERS` is defined, not when `ATLAS_KAFKA_BOOTSTRAP_SERVERS` is defined.

2021-04-28 08:41 UTC, massdosage requested changes
Since this is effectively a backwards-incompatible change we should go with a major version bump and clearly mention this in the CHANGELOG.

2021-05-03 18:00 UTC, barnharts4 reviewed
Looks good except for how to document it in the CHANGELOG in a way that makes sense.

@rpoluri - any suggestions?

2021-05-04 09:25 UTC, massdosage commented on files/startup.sh
> +[[ ! -z $KAFKA_BOOTSTRAP_SERVERS ]] && export AUX_CLASSPATH="$AUX_CLASSPATH:/usr/lib/apiary/kafka-metastore-listener-${APIARY_EXTENSIONS_VERSION}-all.jar:/usr/lib/apiary/kafka-clients-${KAFKA_VERSION
This change to the classpath is also probably worth mentioning in the README as it might change behaviour.

2021-05-04 16:03 UTC, barnharts4 commented on files/startup.sh
> +[[ ! -z $KAFKA_BOOTSTRAP_SERVERS ]] && export AUX_CLASSPATH="$AUX_CLASSPATH:/usr/lib/apiary/kafka-metastore-listener-${APIARY_EXTENSIONS_VERSION}-all.jar:/usr/lib/apiary/kafka-clients-${KAFKA_VERSION
If you look at the change on line 168, I think this change at line 151 is actually just fixing a bug we had where if you defined `KAFKA_BOOTSTRAP_SERVERS` but did *not* define `ATLAS_KAFKA_BOOTSTRAP_SERVERS`, then the classpath would not include `kafka-client.jar`.  We never hit this issue since we defined both for our uses.

2021-05-04 16:18 UTC, massdosage commented on files/startup.sh
> +[[ ! -z $KAFKA_BOOTSTRAP_SERVERS ]] && export AUX_CLASSPATH="$AUX_CLASSPATH:/usr/lib/apiary/kafka-metastore-listener-${APIARY_EXTENSIONS_VERSION}-all.jar:/usr/lib/apiary/kafka-clients-${KAFKA_VERSION
Ah OK, yes, that makes sense, so you don't think it's worth mentioning in the README as a change for anyone who only ever defined `KAFKA_BOOTSTRAP_SERVERS`?

2021-05-04 16:20 UTC, barnharts4 commented on files/startup.sh
> +[[ ! -z $KAFKA_BOOTSTRAP_SERVERS ]] && export AUX_CLASSPATH="$AUX_CLASSPATH:/usr/lib/apiary/kafka-metastore-listener-${APIARY_EXTENSIONS_VERSION}-all.jar:/usr/lib/apiary/kafka-clients-${KAFKA_VERSION
I don't think so, because they would have been broken anyway, and we never got an issue report about it.  So I don't think anyone was using it like that in the first place.

2021-05-04 16:22 UTC, massdosage commented on files/startup.sh
> +[[ ! -z $KAFKA_BOOTSTRAP_SERVERS ]] && export AUX_CLASSPATH="$AUX_CLASSPATH:/usr/lib/apiary/kafka-metastore-listener-${APIARY_EXTENSIONS_VERSION}-all.jar:/usr/lib/apiary/kafka-clients-${KAFKA_VERSION
OK.

2021-05-04 22:39 UTC, barnharts4 submitted a review, later dismissed

2021-05-05 09:40 UTC, massdosage approved these changes

2021-05-05 09:40 UTC, massdosage commented on CHANGELOG.md
> +## [2.0.0] - 2021-05-03
This will obvz need to be updated.

2021-05-06 17:58 UTC, barnharts4 approved these changes

2021-05-06 18:04 UTC, merged