Script for granting restricted sql account in RCP
ExpediaGroup/apiary-metastore-docker pull request #95
Opened 2022-03-11 12:35 UTC by javsanbel2

When hive metastore is executed in read-only mode, we are creating a restricted SQL account with only SELECT permissions to be used.

When hive metastore is executed in read-write mode, we just use the SQL account provided by our secrets.

2022-03-11 15:08 UTC, rpoluri requested changes
this is already handled in apiary-data-lake terraform here
https://github.com/ExpediaGroup/apiary-data-lake/blob/master/scripts/mysql-user.sh

so we should similary using helm init job in RCP

2022-03-11 15:21 UTC, barnharts4 commented on files/startup.sh
> +    /allow-grant-rcp.sh
Additionally, wherever the right change ends up, since this is open-source, we need to name and implement things in a way that is not focused on technologies or services that are internal to EG.

RCP is completely an EG concept, and Vault is not/should not be necessary to run Apiary.

We should do something more like:
```
if [[ -f ${EXTERNAL_CREDENTIALS_FILE} ]]; then
  source ${EXTERNAL_CREDENTIALS_FILE}
fi

...
```

2022-03-14 09:48 UTC, javsanbel2 commented on files/startup.sh
> +    /allow-grant-rcp.sh
You are totally right, Scott, would you take another look at the feature pls?

2022-03-14 09:49 UTC, javsanbel2 commented
> this is already handled in apiary-data-lake terraform here @rpoluri 

Okay, so I will remove the script from here, and I will try to add it as a helm pre-hook in our deployment place, is that okay? thank you

2022-03-14 17:06 UTC, barnharts4 requested changes

2022-03-14 17:06 UTC, barnharts4 commented on files/startup.sh
> +fi
1. If you are wanting to use external credentials instead of reading from AWS secrets manager, then the check to use them must come *before* lines 6-7 where we try to read from AWS secrets manager.  Otherwise we will always be issuing calls to secrets manager which will fail in RCP.
2. Using Secrets manager or external credentials should be an either/or situation, so you want this in an "if-else".  Currently it runs one path, then the other.
3. `-z` tests if a shell variable is *UNDEFINED*.  So your current code is trying to source the `EXTERNAL_CREDENTIALS_FILE` if the variable is *undefined*, which is the opposite of what you want.
4. Use `[[ ]]` instead of `[ ]` to maintain consistency with our script code.
5. Please put `$EXTERNAL_CREDENTIALS_FILE` in double quotes in the `test` statement.  Not having it in quotes can cause errors in certain edge cases when the variable is undefined or zero-length.
6. Since you are using bash indirection syntax here (`${!HM_CUSTOM_USERNAME_VAR_NAME}`), it is unclear what the exact format/syntax of a valid `EXTERNAL_CREDENTIALS_FILE` should be.  This needs to be added to the documentation in `README.md` in the PR.

2022-03-25 14:42 UTC, javsanbel2 commented
Closing this since it won't be needed for now, thanks for the comments

2022-03-25 14:42 UTC, closed without merging